FROM debian:stretch-slim

WORKDIR /work

COPY /tmpinstall /elide/

RUN apt-get update && apt-get install -y \
  graphviz \
  iverilog \
  libftdi1 \
  libtcl8.6 \
  xdot \
 && rm -rf /var/lib/apt/lists/* && apt-get clean all \

#clang bison flex libreadline-dev gawk tcl-dev libffi-dev \
#git mercurial pkg-config python python3 \