FROM debian:stable-slim

RUN apt-get update && apt-get install -y curl \
 && curl -sSL http://fpgalibre.sf.net/debian/go | sh \
 && apt-get update && apt-get install -y apio apio-scons apio-icestorm apio-iverilog apio-examples apio-system \
 && rm -rf /var/lib/apt/lists/* && apt-get clean all \