FROM fedora:latest

WORKDIR /work

COPY /tmpinstall /elide/

RUN dnf install -y \
  graphviz \
  iverilog \
  libftdi \
 && dnf clean all --enablerepo=\* \
 && mkdir -p /etc/udev/rules.d/ \
 && echo 'ACTION=="add", ATTR{idVendor}=="0403", ATTR{idProduct}=="6010", MODE:="666"' > /etc/udev/rules.d/53-lattice-ftdi.rules

# clang bison flex readline-devel gawk tcl-devel libffi-devel \
# python-xdot pkgconfig python python3 which \