FROM debian:stretch-slim

RUN apt-get update && apt-get install -y \
  bison \
  build-essential \
  clang \
  flex \
  git \
  gawk \
  graphviz \
  iverilog \
  libreadline-dev \
  libffi-dev \
  libftdi1-dev \
  mercurial \
  pkg-config \
  python \
  python3 \
  tar \
  tcl-dev \
  xdot \
 && rm -rf /var/lib/apt/lists/* && apt-get clean all \